#ifndef _ULTRASONIC_CONFIG_H_
#define _ULTRASONIC_CONFIG_H_
///***Ultrasonic***/
//启动 检测
#define RCC_ULTRASONIC_TRIG1     RCC_APB2Periph_GPIOA
#define ULTRASONIC_TRIG1_GPIO    GPIOA
#define ULTRASONIC_TRIG1_PIN     GPIO_Pin_11
//返回 信号
#define RCC_ULTRASONIC_ECHO1     RCC_APB2Periph_GPIOA
#define ULTRASONIC_ECHO1_GPIO    GPIOA
#define ULTRASONIC_ECHO1_PIN     GPIO_Pin_8
//启动 检测
#define RCC_ULTRASONIC_TRIG2     RCC_APB2Periph_GPIOA
#define ULTRASONIC_TRIG2_GPIO    GPIOA
#define ULTRASONIC_TRIG2_PIN     GPIO_Pin_10
//返回 信号
#define RCC_ULTRASONIC_ECHO2     RCC_APB2Periph_GPIOA
#define ULTRASONIC_ECHO2_GPIO    GPIOA
#define ULTRASONIC_ECHO2_PIN     GPIO_Pin_9



#endif


